apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hwseo-site-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hse05078@gmail.com
    privateKeySecretRef:
      name: hwseo-ssl-key
    solvers:
      - dns01:
          cloudflare:
            email: hse05078@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

